FROM node:20-slim AS builder

# Instala pacotes necessários para dependências nativas
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    procps \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia arquivos de dependências
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o código fonte
COPY . .

# Build da aplicação
RUN npm run build

# Imagem de desenvolvimento
FROM node:20-slim

# Instala apenas as dependências necessárias
RUN apt-get update && apt-get install -y \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia apenas os arquivos necessários da etapa de build
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/src/core/database/typeorm.config.ts ./src/core/database/typeorm.config.ts
COPY --from=builder /app/src/core/database/migrations ./src/core/database/migrations
COPY --from=builder /app/docs ./docs

# Instala apenas dependências de produção (versão corrigida)
RUN npm install --only=production --no-optional

# Define variáveis de ambiente
ENV NODE_ENV=development

# Expõe a porta da aplicação
EXPOSE 3000

# Comando para iniciar a aplicação em modo desenvolvimento
CMD ["npm", "run", "start:development"]

# teste