FROM node:20-slim

# Instala pacotes necessários para dependências nativas (ex: bcrypt)
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    procps \ 
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

# Define ambiente para instalar devDependencies
ENV NODE_ENV=local

# Instala todas as dependências (incluindo devDependencies)
RUN npm install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "npm run start:${NODE_ENV}"]